server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:questiondb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    org.hibernate.orm.connections.pooling: error


