name: Java CI/CD with Gradle

on:
  pull_request:
    types:
      - opened      # Quando o PR for aberto
      - synchronize # Quando o PR for atualizado
      - reopened    # Quando o PR for reaberto
      - closed      # S처 executa quando o PR for fechado
    branches: [ "master" ]  # Filtra apenas PRs para a branch "master"

jobs:
  # Job de Build
  build:
    runs-on: ubuntu-latest
    environment: secrets
    if: github.event.pull_request.state == 'open'  # Executa apenas quando o PR estiver aberto

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Set execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clear Gradle Cache
        run: ./gradlew clean

      - name: Run tests with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t question-image-ecr .

      - name: Tag Docker image
        run: |
          docker tag question-image-ecr:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/question-image-ecr:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/question-image-ecr:latest

  # Job de Deploy
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # S처 executa o deploy se o PR foi mesclado

    steps:
      - name: Exibir mensagem de deploy
        run: |
          echo "O deploy foi iniciado para a nova vers찾o do c처digo!"
